######################## default configuration ####################
# baseURL = "http://localhost:1313/"
defaultContentLanguage = "th"

title = "THACCA | Thailand Creative Content Agency"
theme = "educenter"
# Default time zone for time stamps; use any valid tz database name: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
timeZone = "Asia/Bangkok"
# post pagination
paginate = 6 # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = 10 # see https://gohugo.io/content-management/excerpts/
# google analytics
# googleAnalytics = "G-Y91RTXE7VX" # example: UA-123456-78, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "themefisher-template" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = ["en", "fr"] # example: ["fr"] for disable french language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false #  If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content. see: https://gohugo.io/getting-started/configuration/#hascjklanguage

############################# Build ##############################
[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = '(js|scripts|javascript)'
[[build.cachebusters]]
source = 'assets/.*\.(css|sass|scss)$'
target = '(css|styles|scss|sass)'
[[build.cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 90
resampleFilter = "lanczos"

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/slick/slick.css"
[[params.plugins.css]]
link = "/plugins/animate/animate.css"
[[params.plugins.css]]
link = "/plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "/plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "/plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "/plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "/plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "/plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "/plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
logo = "/images/logo.png"
# Meta data
description = "THACCA Website"
author = "Strategic Transformation Office & Digital Government Development Agency (Public Organization)"
# contact info
address = ""
mobile = ""
email = "contact@thacca.go.th"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
# google_analitycs_id = "G-Y91RTXE7VX" # your id
# gtm_id = "G-Y91RTXE7VX"
# gtm_ga = true
# top header
top_header = false

# Preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/thaccaofficial"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/thaccaofficial"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/thaccaofficial/"

[[params.social]]
title = "ticktock"
icon = "ti-ticktock" # themify icon : https://themify.me/themify-icons
link = "https://www.tiktok.com/@thaccaofficial"

[[params.social]]
title = "youtube"
icon = "ti-youtube" # themify icon : https://themify.me/themify-icons
link = "https://www.youtube.com/@thaccaofficial"

# [[params.social]]
# title = "github"
# icon = "ti-github" # themify icon : https://themify.me/themify-icons
# link = "#"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
# link = "#"

### Languages 

################################### Thai language #####################################
[Languages.th]
languageName = "TH"
languageCode = "th-TH"
contentDir = "content/thai"
weight = 1

[Languages.th.params]
home = "หน้าหลัก"
# copyright
copyright = "Copyright &copy; 2023 Strategic Transformation Office & Digital Government Development Agency (Public Organization)"

################### Thai navigation ####################

[[Languages.th.menu.main]]
name = "กรรมการ"
url = "/committee/"
weight = 1

[[Languages.th.menu.main]]
name = "ข่าวสาร"
url = "/news/"
weight = 2

[[Languages.th.menu.main]]
name = "บทความ"
url = "/article/"
weight = 3

# main menu
[[Languages.th.menu.main]]
name = "เกี่ยวกับเรา"
url = "/about/"
weight = 4

# [[Languages.en.menu.main]]
# weight = 3
# name = "Pages"
# hasChildren = true

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "teacher"
#   url = "teacher/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "notice"
#   url = "notice/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "event"
#   url = "event/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "scholarship"
#   url = "scholarship/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "research"
#   url = "research/"
  
# [[Languages.en.menu.main]]
# name = "blog"
# url = "blog/"
# weight = 4
  
# [[Languages.en.menu.main]]
# name = "Contact"
# url = "contact/"
# weight = 5

# footer menu

# [[Languages.th.menu.footer]]
# name = "teacher"
# url = "teacher/"

# [[Languages.th.menu.footer]]
# name = "notice"
# url = "notice/"

# [[Languages.th.menu.footer]]
# name = "event"
# url = "event/"

# [[Languages.th.menu.footer]]
# name = "scholarship"
# url = "scholarship/"

# [[Languages.th.menu.footer]]
# name = "research"
# url = "research/"

################################### English language #####################################
[Languages.en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 2

[Languages.en.params]
home = "Home"
# copyright
copyright = "Copyright &copy; 2023 Digital Government Development Agency (Public Organization)"

################### English navigation ####################

[[Languages.en.menu.main]]
name = "Events"
url = "event/"
weight = 1

[[Languages.en.menu.main]]
name = "News"
url = "news/"
weight = 1

[[Languages.en.menu.main]]
name = "article"
url = "article/"
weight = 2

# main menu
[[Languages.en.menu.main]]
name = "About"
url = "about/"
weight = 3

# [[Languages.en.menu.main]]
# weight = 3
# name = "Pages"
# hasChildren = true

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "teacher"
#   url = "teacher/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "notice"
#   url = "notice/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "event"
#   url = "event/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "scholarship"
#   url = "scholarship/"

#   [[Languages.en.menu.main]]
#   parent = "Pages"
#   name = "research"
#   url = "research/"
  
# [[Languages.en.menu.main]]
# name = "blog"
# url = "blog/"
# weight = 4
  
# [[Languages.en.menu.main]]
# name = "Contact"
# url = "contact/"
# weight = 5


# footer menu

# [[Languages.en.menu.footer]]
# name = "teacher"
# url = "teacher/"

# [[Languages.en.menu.footer]]
# name = "notice"
# url = "notice/"

# [[Languages.en.menu.footer]]
# name = "event"
# url = "event/"

# [[Languages.en.menu.footer]]
# name = "scholarship"
# url = "scholarship/"

# [[Languages.en.menu.footer]]
# name = "research"
# url = "research/"



################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 3

[Languages.fr.params]
home = "Accueil"
# copyright
copyright = "Copyright &copy; 2021 a hugo theme by [Themefisher](https://themefisher.com/hugo-themes/)"



################### French navigation ####################

# main menu
[[Languages.fr.menu.main]]
name = "À propos"
url = "about/"
weight = 1

[[Languages.fr.menu.main]]
name = "Cours"
url = "course/"
weight = 2

[[Languages.fr.menu.main]]
weight = 3
name = "Pages"
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "teacher"
  url = "teacher/"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "notice"
  url = "notice/"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Évènement"
  url = "event/"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "Cursus"
  url = "scholarship/"

  [[Languages.fr.menu.main]]
  parent = "Pages"
  name = "research"
  url = "research/"
  
[[Languages.fr.menu.main]]
name = "blog"
url = "blog/"
weight = 4
  
[[Languages.fr.menu.main]]
name = "Contact"
url = "contact/"
weight = 5


# footer menu

[[Languages.fr.menu.footer]]
name = "teacher"
url = "teacher/"

[[Languages.fr.menu.footer]]
name = "notice"
url = "notice/"

[[Languages.fr.menu.footer]]
name = "event"
url = "event/"

[[Languages.fr.menu.footer]]
name = "scholarship"
url = "scholarship/"

[[Languages.fr.menu.footer]]
name = "research"
url = "research/"
