backend:
  name: github
  repo: DGA-Thailand/thacca
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/images
public_folder: /images
slug:
  encoding: 'unicode'
  sanitize_replacement: '-'
collections:
  - name: 'article'
    label: 'Articles (Thai)'
    folder: 'content/thai/article'
    identifier_field: 'title'
    create: true
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image', media_folder: '/static/images/article/', public_folder: '/images/article/' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', timeFormat: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Tags', name: 'tags', options: ["committee", "subcommittee", "ofos", "people", "collaboration", "knowledge", "splash", "arts", "book", "design", "fashion", "festival", "film", "food", "music", "series", "sport", "tourism"], widget: "select", multiple: true, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'news'
    label: 'News (Thai)'
    folder: 'content/thai/news'
    create: true
    identifier_field: 'title'
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image', media_folder: '/static/images/news/', public_folder: '/images/news/' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', timeFormat: false }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }
      - { label: 'Tags', name: 'tags', options: ["committee", "subcommittee", "ofos", "people", "collaboration", "knowledge", "splash", "arts", "book", "design", "fashion", "festival", "film", "food", "music", "series", "sport", "tourism"], widget: "select", multiple: true, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'committee'
    label: 'Committe (Thai)'
    folder: 'content/thai/committee'
    create: true
    identifier_field: 'title'
    slug: "{{slug}}"
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image', media_folder: '/static/images/news/', public_folder: '/images/news/', required: false }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', format: 'YYYY-MM-DD', timeFormat: false  }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Tags', name: 'tags', options: ["committee", "subcommittee", "ofos", "people", "collaboration", "knowledge", "arts", "book", "design", "fashion", "festival", "film", "food", "music", "series", "sport", "tourism"], widget: "select", multiple: true, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'about'
    label: 'About (Thai)'
    folder: 'content/thai/about'
    create: true
    identifier_field: 'title'
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Featured Image', name: 'image', widget: 'image', media_folder: '/static/images/about/', public_folder: '/images/about/', required: false }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }